### ISSUE TITLE
Importing private keys into BCX desktop wallet

### ISSUE THREAD

**Issue by CryptoFinesse** [bitcoinx-project/bitcoinx#14]
To whom it may concern. Could you please provide with me some information on how to import private keys into the BCX wallet. I like the idea of this project and would like to claim the tokens. I held BTC in a paper wallet at the time of this fork. Any help would be greatly appreciated.

keep up the good work

(From my understanding I need to enter a command into the command console followed by the private key that held the BCX? If so could someone be kind enough to explain in simple terms how to perform such a process xx)

**Comment by valyriasteel** [comment]
@CryptoFinesse try this: `importprivkey "your-private-key"`

**Comment by CryptoFinesse** [comment]
Hi,

Thank you kindly for the reply. Should I wait for it to fully sync before entering the command. Do I enter this into the Debug window on the wallet ?

Sent from my iPhone

On 20 Jan 2018, at 15:39, valyriasteel <notifications@github.com<mailto:notifications@github.com>> wrote:


@CryptoFinesse<https://github.com/cryptofinesse> try this: importprivkey "your-private-key"

**Comment by valyriasteel** [comment]
@CryptoFinesse you can import your private key in the debug window at anytime, and the balance will be updated during sync.

**Comment by tnkmt** [comment]
First turn on encryption of your wallet.

Then, backup your wallet.dat.

Then, backup your password.

Then, verify that you backed up the correct wallet and verify that you can open it with your backed up password.

And only when you are sure you made a backup of your wallet.dat (and your password), you can continue with moving funds to your new wallet.

And never delete your old private keys.

Please note that your imported private key is not backed up because you made the backup before to import it. You need to transfer the coins from this key to your new address to make sure your coins are in the backed up wallet.dat.

(I did not tested it and don't know if it is HD wallet or not, in case it is not - you need to backup your wallet.dat regularly because there is a limited number of addresses in the backup.)
